server:
  port: 8071
# 开发环境配置
spring:
    profiles:
        active: dev
    data:
        hbase:
            quorum: nn1,nn2,dn1,dn2,dn3,dn4,dn5
            rootDir: hdfs://nn1:8020
            nodeParent: /hbase


